services:
  - type: web
    name: findai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --timeout 200 --workers 1 --threads 8
    plan: free
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
